### ISSUE TITLE
Why is master always headless?

### ISSUE THREAD

**Issue by saveshodhan** [SvenskaSpel/locust-swarm#10]
I was wondering why do we have `--headless` hard-coded in the master command ([here](https://github.com/SvenskaSpel/locust-swarm/blob/master/bin/swarm#L375)).
It is accepted as an argument, but the value is not used. Are there any issues that any one faced because of which this decision was made?

**Comment by saveshodhan** [comment]
Asking because I need the url so that i can forward it using [`locust_exporter`](https://github.com/ContainerSolutions/locust_exporter)

**Comment by cyberw** [comment]
I always run headless because I have a separate reporting solution :) 

I think you can override it with --headful (which takes priority over headless)

**Comment by saveshodhan** [comment]
aha! `--headful` works. thanks!

**Comment by saveshodhan** [comment]
closing this issue, thanks for your help @cyberw!
