### ISSUE TITLE
gods, this is an awesome lib.  btw, call this program support WebUI pattern?

### ISSUE THREAD

**Issue by XZ175411** [SvenskaSpel/locust-swarm#11]

**Comment by cyberw** [comment]
Thanks! Yes! But since --headless is its default, you need to pass a `--headful` parameter to override that.

**Comment by wallacekabum** [comment]
hello i also need this functionality. However, analyzing the source code, I saw that --headless is being called directly in the ssh command. I tested it with --headful and was not successful.

Follow the path: https://github.com/SvenskaSpel/locust-swarm/blob/master/bin/swarm#L242

**Comment by cyberw** [comment]
if you pass --headful, locust should receive both parameters and headful should take priority. Can you show me the output?

**Comment by wallacekabum** [comment]
init Command:
`swarm -t 10 --loadgen-list 10.70.#.# --loadgens 1 --processes-per-loadgen 16 --headful -f 01_banner_v1.py`

Error Return:
```
raise subprocess.CalledProcessError(retcode, process.args)
subprocess.CalledProcessError: Command 'ssh -q 10.70.#.# ' LOCUST_RUN_ID="2021-12-13T21:03:30.632264+00:00" PYTHONUNBUFFERED=1 locust --worker --master-port 5557 --headless -f 01_banner_v1.py --headful & read; kill -9 $! '' returned non-zero exit status 255.
```

**Comment by wallacekabum** [comment]
The sequence insert --headful is wrong ?  ... has to be before the -f argument

**Comment by cyberw** [comment]
There should be an additional error message in the output before that. If not, try executing the exact ssh command manually and see what it says.
