### ISSUE TITLE
LOADGEN_ List parameter format

### ISSUE THREAD

**Issue by dzjwwm** [SvenskaSpel/locust-swarm#12]
To connect to SSH, you need to provide the user name, password and port, then loadgen_ What is the format of the list parameter?

**Comment by cyberw** [comment]
Comma separated. E.g `server1.domain.com,server2.domain.com`

You *should* be able to use username@server1.domain.com,username@server2… 

For password-protected keys you must use ssh-agent, maybe it can work for regular passwords as well, but using password based ssh auth is not really good practice, so I dont care top much about supporting it :)
