### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by chrishare08** [SvenskaSpel/locust-swarm#2]
the lack of documentation to set this up and make it work is disappointing. "try it out and see what is missing" isn't very helpful.

**Comment by cyberw** [comment]
Uhm, I'm sorry this free and open source project is disappointing to you.

If you're referring to "Just try running it and you'll get feedback on what is missing", I juste meant that users should be able to discover any mandatory parameters/env vars based on the errors they get.

If you have a specific issue/feature that you find hard to understand, let me know.
