### ISSUE TITLE
No support for explicitly provided SSH port to connect to.

### ISSUE THREAD

**Issue by toponim** [SvenskaSpel/locust-swarm#21]
Some internal networks use non-default SSH port for security reasons. While SSH can be configured using ~/.ssh/config it may be desirable to explicitly provide port via command line, for example to make CI/CD pipeline easily transferable between build nodes.

Please consider patch below for proposed changes: [ssh_port.patch](https://github.com/user-attachments/files/17093733/ssh_port.patch)

**Comment by cyberw** [comment]
Makes sense. Can you make a PR and I'll review?

**Comment by toponim** [comment]
> Makes sense. Can you make a PR and I'll review?

I've got denied error when trying to push a branch. Is it possible to write to your project or you would like me consider PR from a fork?

**Comment by cyberw** [comment]
PR from a fork would be perfect!

**Comment by toponim** [comment]
Please consider https://github.com/SvenskaSpel/locust-swarm/pull/23 for review once you have a time.
