### ISSUE TITLE
what are loadgens and where do i get one?

### ISSUE THREAD

**Issue by chrishare08** [SvenskaSpel/locust-swarm#3]
not sure what is supposed to go into the loadgens variable

usage: swarm [-h] [-f TESTPLAN] [-t RUN_TIME] [-u USERS]
             [--headless IGNORE_THIS]
             [--processes-per-loadgen PROCESSES_PER_LOADGEN]
             [--loadgens LOADGENS] [--loadgen-list LOADGEN_LIST]
             [-L LOGLEVEL] [--port PORT] [--jmeter] [--jmeter-gui]
             [--jmeter-kill-first] [--remote-master REMOTE_MASTER]
swarm: error: No loadgens specified on command line (--loadgen-list) or env var (LOADGEN_LIST). Use a comma-separated list.

**Comment by cyberw** [comment]
A comma separated list of servers, which swarm will connect to over ssh. 

e.g loadgen1.mydomain.com,loadgen2.mydomain.com

**Comment by chrishare08** [comment]
ok - so basically the IPs, or hostnames of the servers which locust will run on.
