### ISSUE TITLE
JMETER_MASTER environment variable

### ISSUE THREAD

**Issue by chrishare08** [SvenskaSpel/locust-swarm#4]
why does locust need JMeter?  We are using locust to AVOID using JMeter

**Comment by cyberw** [comment]
Swarm doesnt need jmeter, it just supports it. But I’m removing support for jmeter, so soon you will not see it any more..

**Comment by chrishare08** [comment]
ok - I did a pull and i am writing some docs which i will push back eventually :-)

**Comment by chrishare08** [comment]
ok - I'll trick it for now my defining a variable with no value :-)
