### ISSUE TITLE
ssh access denied - swarm should allow for the definition of the ssh key on the command line

### ISSUE THREAD

**Issue by chrishare08** [SvenskaSpel/locust-swarm#5]
my ssh keys are in /.ssh directory.  When I run swarm, it cannot connect to the remote IP because there is no option to provide the specific key to use for the loadgens on the command line.

How do keys get associated with loadgens, especially if the keys are different as they would be in different AWS regions?

## what happens
```
chare@172.31.10.171: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
2020-06-15:11:38:08,873 ERROR [swarm:85] Error ssh:ing to loadgen (172.31.10.171). Maybe you dont have permission to log on to them? Or your ssh key requires a password? (in that case, use ssh-agent)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/swarm", line 83, in <module>
    subprocess.check_output(f"ssh -o LogLevel=error -o BatchMode=yes {ssh_test_server} true", shell=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gevent/subprocess.py", line 389, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command 'ssh -o LogLevel=error -o BatchMode=yes 172.31.10.171 true' returned non-zero exit status 255.
```

## what should happen 

```
swarm <options> -k ssh-key.pem file
```

This would be especially useful on AWS where there is a key used for a group of machines.  Of course, if your loadgens are in different AWS regions, different AWS keys will be needed per region.

**Comment by cyberw** [comment]
I think you can work around it using ssh-agent

If you want something like a -k parameter to support specifying a key, feel free to build it and PR, it would be much appreciated!
