### ISSUE TITLE
does swarm the defined number of users on each loadgen?

### ISSUE THREAD

**Issue by chrishare08** [SvenskaSpel/locust-swarm#6]
if I run swarm with 

```
swarm --users 1000 --loadgens=2
```

does it split that 1000 users across the 2 loadgens, or does it run 1000 users on each loadgen?

**Comment by cyberw** [comment]
Locust (whether started with swarm or not) always divides the number of users you specified across all the worker processes.

I understand that this tool is useful for you and I’m happy that you use it, but please spend some time to try to figure things out yourself before posting an issue. Dont expect me to respond as quickly to future tickets.
