### ISSUE TITLE
Locust location not present in $PATH

### ISSUE THREAD

**Issue by saveshodhan** [SvenskaSpel/locust-swarm#9]
Hello there,

I have few EC2 instances (as workers) on which i installed `locust` and have `rsync`'d the relevant files.
When I try to run `swarm` it throws error as it's not able to locate locust in any of the locations mentioned in PATH.

After trying few things I realised that the shell that `ssh` gets does not have the path where locust is installed, as it's not a login shell ([this SO link](https://stackoverflow.com/a/216204/4260095) helped):

For eg., consider the below where PATH gets less values:
```
$ ssh user@host 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

And when I do the below I get all values, one of which contain `locust`:
```
$ ssh user@host
user@host:~$ echo $PATH
/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/.local/bin
```
Any idea how can I get around this? I dont think I have enough rights to copy `locust` to `/usr` locations..

**Comment by cyberw** [comment]
Hmm, without root I think you're stuck. If you have root you might be able to do stuff in `/etc/environment` (which is supposedly read in all shells, even non-login shells, at least on ubuntu). Or you can install locust with `sudo pip3 install locust` (you'll get lots of warnings about why it is a bad idea to run pip as root, but I think they can be ignored in this case)

**Comment by cyberw** [comment]
Ah, wait, the best way to do it is just to specify the correct path in ~/.bashrc on the remote (as that one is read by bash even for non-login non-interactive shells)

**Comment by cyberw** [comment]
Most likely pip will have place the binary in `/home/<user>/.local/bin`, so that is the one you need to add to your PATH

**Comment by saveshodhan** [comment]
@cyberw i added it in `/.bashrc`, still doesnt work. i think the bashrc in the home location works only for interactive shell - i added an echo, and it echoes only during interactive shell

**Comment by cyberw** [comment]
Did you put it in `~/.bashrc` or `/.bashrc`?

**Comment by cyberw** [comment]
at least it worked for me...

**Comment by saveshodhan** [comment]
Oh sorry, it was `~/.bashrc`. I'll check more to see if I can get something. Thanks for your prompt help though!

**Comment by cyberw** [comment]
I got the inspiration here: https://superuser.com/a/1224962/256930

**Comment by cyberw** [comment]
Perhaps bash is not your default shell or something?

**Comment by saveshodhan** [comment]
@cyberw i moved the export command at the top, in the .bashrc file, and it worked! I still need to figure out why this worked 😅

**Comment by saveshodhan** [comment]
Closing this issue..
